# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: InvoiceNinja dockerizing

on:
  push:
    branches: [ "master" ] # XXX TODO 2DELETE - only for initial debugging

jobs:
  # parse_tags:
  #   name: DEP! Parse date && trm file ID in triggered ref
  #   runs-on: ubuntu-latest
  #   env:
  #     JOB_REF: "20210708-141FTb"
  #     # JOB_REF: ${{ github.ref }}
  #   outputs:
  #     build_tag: ${{ steps.get-tag-from-ref.outputs.build_tag }}
  #     build_trmid: ${{ steps.get-trmid-from-tag.outputs.build_trmid }}
  #     build_date: ${{ steps.get-date-from-tag.outputs.build_date }}
  #   steps:
  #   - id: get-tag-from-ref
  #     run: echo "::set-output name=build_tag::${JOB_REF##*/}"
  #   - id: get-trmid-from-tag
  #     run: a="${{ steps.get-tag-from-ref.outputs.build_tag }}" ; echo "::set-output name=build_trmid::${a#*-}"
  #   - id: get-date-from-tag
  #     run: a="${{ steps.get-tag-from-ref.outputs.build_tag }}" ; echo "::set-output name=build_date::${a%-*}"
  #   - run: echo ${{ env.JOB_REF }}
  #   - run: echo ${{ steps.get-tag-from-ref.outputs.build_tag }}
  #   - run: echo ${{ steps.get-trmid-from-tag.outputs.build_trmid }}
  #   - run: echo ${{ steps.get-date-from-tag.outputs.build_date }}
  build_base:
    name: Build invoiceninja docker image
    runs-on: ubuntu-latest
    # needs: [ parse_tags ]
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: registry.is-docker.mh00p.net
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - run: ls -lah ; pwd
    - uses: docker/build-push-action@master
      with:
        context: .
        push: true
        tags: registry.is-docker.mh00p.net/invoiceninja-frontend:latest,registry.is-docker.mh00p.net/invoiceninja-backend:latest
        # ,registry.is-docker.mh00p.net/tsn:${{ needs.parse_tags.outputs.build_date }}-${{ github.run_id }}
